HASH_DB_NAME = "hash_storage.db"
# 8 MiB in bytes
MAX_MESSAGE_LENGTH = 8_388_608
SALT_SIZE = 8
HASH_DB_TABLE_NAME = "hash_storage"
ACCOUNT_STORAGE_DB_NAME = "account_storage.db"
ACCOUNT_STORAGE_DB_TABLE = "accounts"
ARGON2ID_TIME_COST = 3
ARGON2ID_MEMORY_COST = 65536
ARGON2ID_PARALLELISM = 4
